CREATE SCHEMA LoLDB;
GO

CREATE TABLE LoLDB.Region (
    RegionID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [Name] NVARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE LoLDB.Champion (
    ChampionID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [Name] NVARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE LoLDB.Position (
    PositionID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [Name] NVARCHAR(64) NOT NULL UNIQUE,
    LogoLink VARCHAR(256) NOT NULL,
);

CREATE TABLE LoLDB.Team (
    TeamID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    RegionID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.Region(RegionID),
    [Name] NVARCHAR(64) NOT NULL UNIQUE,
    LogoLink VARCHAR(256) NOT NULL,
    NameAbbreviation NVARCHAR(64) NOT NULL,
);

CREATE TABLE LoLDB.Player (
    PlayerID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [Name] NVARCHAR(64) NOT NULL UNIQUE,
    PositionID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.Position(PositionID),
    TeamID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.Team(TeamID),
);

CREATE TABLE LoLDB.Game (
    GameID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    StartDateTime DATETIMEOFFSET NOT NULL,
    Duration TIME NOT NULL
);

CREATE TABLE LoLDB.PlayerGameStat (
    PlayerGameStatID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    ChampionID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.Champion(ChampionID),
    GameID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.Game(GameID),
    PlayerID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.Player(PlayerID),
    CreepScore INT NOT NULL,
    VisionScore INT NOT NULL,
    [10MinuteGold] INT,
    [15MinuteGold] INT,
    EndGold INT NOT NULL,

    UNIQUE (
        GameID, PlayerID
    )
);

CREATE TABLE LoLDB.RunePath (
    RunePathID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [Name] NVARCHAR(64) NOT NULL UNIQUE,
    LogoLink VARCHAR(256) NOT NULL,
);

CREATE TABLE LoLDB.KeystoneRune (
    KeystoneRuneID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [Name] NVARCHAR(64) NOT NULL UNIQUE,
    LogoLink VARCHAR(256) NOT NULL,
    RunePathID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.RunePath(RunePathID)
);

CREATE TABLE LoLDB.SecondaryRune (
    SecondaryRuneID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [Name] NVARCHAR(64) NOT NULL UNIQUE,
    LogoLink VARCHAR(256) NOT NULL,
    Slot TINYINT NOT NULL CHECK(Slot BETWEEN 1 AND 3),
    RunePathID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.RunePath(RunePathID)
);

CREATE TABLE LoLDB.ShardRune (
    ShardRuneID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [Name] NVARCHAR(64) NOT NULL UNIQUE,
    LogoLink VARCHAR(256) NOT NULL,
    Slot TINYINT NOT NULL CHECK(Slot BETWEEN 1 AND 3)
);

CREATE TABLE LoLDB.PlayerKeystone (
    PlayerGameStatID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.PlayerGameStat(PlayerGameStatID),
    KeystoneRuneID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.KeystoneRune(KeystoneRuneID),

    PRIMARY KEY (PlayerGameStatID, KeystoneRuneID)
);

CREATE TABLE LoLDB.PlayerSecondaryRunePath (
    PlayerGameStatID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.PlayerGameStat(PlayerGameStatID),
    PlayerSecondaryRunePathID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.RunePath(RunePathID),

    PRIMARY KEY (PlayerGameStatID, PlayerSecondaryRunePathID)
);

CREATE TABLE LoLDB.PlayerSecondaryRune (
    PlayerGameStatID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.PlayerGameStat(PlayerGameStatID),
    PlayerSecondaryRuneID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.SecondaryRune(SecondaryRuneID),

    PRIMARY KEY (PlayerGameStatID, PlayerSecondaryRuneID)
);

CREATE TABLE LoLDB.PlayerShard (
    PlayerGameStatID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.PlayerGameStat(PlayerGameStatID),
    ShardRuneID INT NOT NULL FOREIGN KEY REFERENCES LoLDB.ShardRune(ShardRuneID),

    PRIMARY KEY (PlayerGameStatID, ShardRuneID)
);
