DELETE FROM LoLDB.Position;
DBCC CHECKIDENT ('LoLDB.Position', RESEED, 1);
DELETE FROM LoLDB.Champion;
DBCC CHECKIDENT ('LoLDB.Champion', RESEED, 1);
DELETE FROM LoLDB.SecondaryRune;
DBCC CHECKIDENT ('LoLDB.SecondaryRune', RESEED, 1);
DELETE FROM LoLDB.KeystoneRune;
DBCC CHECKIDENT ('LoLDB.KeystoneRune', RESEED, 1);
DELETE FROM LoLDB.RunePath;
DBCC CHECKIDENT ('LoLDB.RunePath', RESEED, 1);
DELETE FROM LoLDB.ShardRune;
DBCC CHECKIDENT ('LoLDB.ShardRune', RESEED, 1);
DELETE FROM LoLDB.Region;
DBCC CHECKIDENT ('LoLDB.Region', RESEED, 1);
DELETE FROM LoLDB.Location;
DBCC CHECKIDENT ('LoLDB.Region', RESEED, 1);
DELETE FROM LoLDB.Objective;
DBCC CHECKIDENT ('LoLDB.Objective', RESEED, 1);
DELETE FROM LoLDB.ItemQuality;
DBCC CHECKIDENT ('LoLDB.ItemQuality', RESEED, 1);


INSERT INTO LoLDB.Region([Name])
VALUES
    ('North America'), ('Europe'), ('LCL'), ('Japan'), ('Oceania'), ('Brazil'), ('Turkey'), ('China'), ('Korea');

INSERT INTO LoLDB.RunePath([Name], LogoLink)
VALUES
    ('Precision', 'https://static.wikia.nocookie.net/leagueoflegends/images/2/26/Precision_icon.png/revision/latest/'),
    ('Domination', 'https://static.wikia.nocookie.net/leagueoflegends/images/1/1e/Domination_icon.png/revision/latest'),
    ('Sorcery', 'https://static.wikia.nocookie.net/leagueoflegends/images/c/cd/Sorcery_icon.png/revision/latest/'),
    ('Resolve', 'https://static.wikia.nocookie.net/leagueoflegends/images/f/fa/Resolve_icon.png/revision/latest/'),
    ('Inspiration', 'https://static.wikia.nocookie.net/leagueoflegends/images/0/0d/Inspiration_icon.png/revision/latest/');

INSERT INTO LoLDB.KeystoneRune([Name], LogoLink, RunePathID)
SELECT D.[Name], D.LogoLink, RunePathID
FROM (
    VALUES ('Press the Attack', 'Precision', 'link-add-later'),
        ('Lethal Tempo', 'Precision', 'link-add-later'),
	('Fleet Footwork', 'Precision', 'link-add-later'),
	('Conqueror', 'Precision', 'link-add-later'),
        ('Electrocute', 'Domination', 'link-add-later'),
        ('Hail of Blades', 'Domination', 'link-add-later'),
        ('Predator', 'Domination', 'link-add-later'),
        ('Dark Harvest', 'Domination', 'link-add-later'),
        ('Phase Rush', 'Sorcery', 'link-add-later'),
        ('Arcane Comet', 'Sorcery', 'link-add-later'),
        ('Summon Aery', 'Sorcery', 'link-add-later'),
        ('Grasp of the Undying', 'Resolve', 'link-add-later'),
        ('Aftershock', 'Resolve', 'link-add-later'),
        ('Guardian', 'Resolve', 'link-add-later'),
        ('Prototype: Omnistone', 'Inspiration', 'link-add-later'),
        ('Glacial Augment', 'Inspiration', 'link-add-later'),
        ('Unsealed Spellbook', 'Inspiration', 'link-add-later')
) D([Name], RunePathName, LogoLink)
JOIN LoLDB.RunePath RP ON D.RunePathName = RP.Name;

INSERT INTO LoLDB.SecondaryRune([Name], Slot, LogoLink, RunePathID)
SELECT D.[Name], Slot, D.LogoLink, RunePathID
FROM (
    VALUES ('Overheal', 'Precision', 1, 'link-add-later'),
	('Triumph', 'Precision', 1, 'link-add-later'),
	('Presence of Mind', 'Precision', 1, 'link-add-later'),
        ('Legend: Alacrity', 'Precision', 2, 'link-add-later'),
        ('Legend: Tenacity', 'Precision', 2, 'link-add-later'),
        ('Legend: Bloodline', 'Precision', 2, 'link-add-later'),
        ('Coup De Grace', 'Precision', 3, 'link-add-later'),
        ('Cut Down', 'Precision', 3, 'link-add-later'),
        ('Last Stand', 'Precision', 3, 'link-add-later'),
        ('Cheap Shot', 'Domination', 1, 'link-add-later'),
        ('Taste of Blood', 'Domination', 1, 'link-add-later'),
        ('Sudden Impact', 'Domination', 1, 'link-add-later'),
        ('Zombie Ward', 'Domination', 2, 'link-add-later'),
        ('Ghost Poro', 'Domination', 2, 'link-add-later'),
        ('Eyeball Collection', 'Domination', 2, 'link-add-later'),
        ('Ravenous Hunter', 'Domination', 3, 'link-add-later'),
        ('Ingenious Hunter', 'Domination', 3, 'link-add-later'),
        ('Relentless Hunter', 'Domination', 3, 'link-add-later'),
        ('Ultimate Hunter', 'Domination', 3, 'link-add-later'),
        ('Nullifying Orb', 'Sorcery', 1, 'link-add-later'),
        ('Manaflow Band', 'Sorcery', 1, 'link-add-later'),
        ('Nimbus Cloak', 'Sorcery', 1, 'link-add-later'),
        ('Transcendence', 'Sorcery', 2, 'link-add-later'),
        ('Celerity', 'Sorcery', 2, 'link-add-later'),
        ('Absolute Focus', 'Sorcery', 2, 'link-add-later'),
        ('Scorch', 'Sorcery', 3, 'link-add-later'),
        ('Waterwalking', 'Sorcery', 2, 'link-add-later'),
        ('Gathering Storm', 'Sorcery', 2, 'link-add-later'),
        ('Demolish', 'Resolve', 1, 'link-add-later'),
        ('Font of Life', 'Resolve', 1, 'link-add-later'),
        ('Shield Bash', 'Resolve', 1, 'link-add-later'),
        ('Conditioning', 'Resolve', 2, 'link-add-later'),
        ('Second Wind', 'Resolve', 2, 'link-add-later'),
        ('Bone Plating', 'Resolve', 2, 'link-add-later'),
        ('Overgrowth', 'Resolve', 3, 'link-add-later'),
        ('Revitalize', 'Resolve', 3, 'link-add-later'),
        ('Unflinching', 'Resolve', 3, 'link-add-later'),
        ('Hextech Flashtraption', 'Inspiration', 1, 'link-add-later'),
        ('Magical Footwear', 'Inspiration', 1, 'link-add-later'),
        ('Perfect Timing', 'Inspiration', 1, 'link-add-later'),
        ('Future''s Market', 'Inspiration', 2, 'link-add-later'),
        ('Minion Dematerializer', 'Inspiration', 2, 'link-add-later'),
        ('Biscuit Delivery', 'Inspiration', 2, 'link-add-later'),
        ('Cosmic Insight', 'Inspiration', 3, 'link-add-later'),
        ('Approach Velocity', 'Inspiration', 3, 'link-add-later'),
        ('Time Warp Tonic', 'Inspiration', 3, 'link-add-later')
) D([Name], RunePathName, Slot, LogoLink)
JOIN LoLDB.RunePath RP ON D.RunePathName = RP.Name;

INSERT INTO LoLDB.ShardRune([Name], Slot, LogoLink)
VALUES
    ('Adaptive Force', 1, 'link-add-later'),
    ('Attack Speed', 1, 'link-add-later'),
    ('Ability Haste', 1, 'link-add-later'),
    ('Adapative Force', 2, 'link-add-later'),
    ('Armor', 2, 'link-add-later'),
    ('Magic Resist', 2, 'link-add-later'),
    ('Health', 3, 'link-add-later'),
    ('Armor', 3, 'link-add-later'),
    ('Magic Resist', 3, 'link-add-later');

INSERT INTO LoLDB.Position([Name], LogoLink)
VALUES
    ('Top', 'link-add-later'),
    ('Jungle', 'link-add-later'),
    ('Mid', 'link-add-later'),
    ('ADC', 'link-add-later'),
    ('Support', 'link-add-later'),
    ('Coach', 'link-add-later');

INSERT INTO LoLDB.Champion([Name])
VALUES
    ('Aatrox'),
    ('Ahri'),
    ('Akali'),
    ('Akshan'),
    ('Alistar'),
    ('Amumu'),
    ('Anivia'),
    ('Annie'),
    ('Aphelios'),
    ('Ashe'),
    ('Aurelion Sol'),
    ('Azir'),
    ('Bard'),
    ('Blitzcrank'),
    ('Brand'),
    ('Braum'),
    ('Caitlyn'),
    ('Camille'),
    ('Cassiopeia'),
    ('Cho''Gath'),
    ('Corki'),
    ('Darius'),
    ('Diana'),
    ('Draven'),
    ('Dr. Mundo'),
    ('Ekko'),
    ('Elise'),
    ('Evelynn'),
    ('Ezreal'),
    ('Fiddlesticks'),
    ('Fiora'),
    ('Fizz'),
    ('Galio'),
    ('Gangplank'),
    ('Garen'),
    ('Gnar'),
    ('Gragas'),
    ('Graves'),
    ('Gwen'),
    ('Hecarim'),
    ('Heimerdinger'),
    ('Illaoi'),
    ('Irelia'),
    ('Ivern'),
    ('Janna'),
    ('Jarvan IV'),
    ('Jax'),
    ('Jayce'),
    ('Jhin'),
    ('Jinx'),
    ('Kai''Sa'),
    ('Kalista'),
    ('Karma'),
    ('Karthus'),
    ('Kassadin'),
    ('Katarina'),
    ('Kayle'),
    ('Kayn'),
    ('Kennen'),
    ('Kha''Zix'),
    ('Kindred'),
    ('Kled'),
    ('Kog''Maw'),
    ('LeBlanc'),
    ('Lee Sin'),
    ('Leona'),
    ('Lillia'),
    ('Lissandra'),
    ('Lucian'),
    ('Lulu'),
    ('Lux'),
    ('Malphite'),
    ('Malzahar'),
    ('Maokai'),
    ('Master Yi'),
    ('Miss Fortune'),
    ('Mordekaiser'),
    ('Morgana'),
    ('Nami'),
    ('Nasus'),
    ('Nautilus'),
    ('Neeko'),
    ('Nidalee'),
    ('Nocturne'),
    ('Nunu & Willump'),
    ('Olaf'),
    ('Orianna'),
    ('Ornn'),
    ('Pantheon'),
    ('Poppy'),
    ('Pyke'),
    ('Qiyana'),
    ('Quinn'),
    ('Rakan'),
    ('Rammus'),
    ('Rek''Sai'),
    ('Rell'),
    ('Renekton'),
    ('Rengar'),
    ('Riven'),
    ('Rumble'),
    ('Ryze'),
    ('Samira'),
    ('Sejuani'),
    ('Senna'),
    ('Seraphine'),
    ('Sett'),
    ('Shaco'),
    ('Shen'),
    ('Shyvana'),
    ('Singed'),
    ('Sion'),
    ('Sivir'),
    ('Skarner'),
    ('Sona'),
    ('Soraka'),
    ('Swain'),
    ('Sylas'),
    ('Syndra'),
    ('Tahm Kench'),
    ('Taliyah'),
    ('Talon'),
    ('Taric'),
    ('Teemo'),
    ('Thresh'),
    ('Tristana'),
    ('Trundle'),
    ('Tryndamere'),
    ('Twisted Fate'),
    ('Twitch'),
    ('Udyr'),
    ('Urgot'),
    ('Varus'),
    ('Vayne'),
    ('Veigar'),
    ('Vel''Koz'),
    ('Vex'),
    ('Vi'),
    ('Viego'),
    ('Viktor'),
    ('Vladimir'),
    ('Volibear'),
    ('Warwick'),
    ('Wukong'),
    ('Xayah'),
    ('Xerath'),
    ('Xin Zhao'),
    ('Yasuo'),
    ('Yone'),
    ('Yorick'),
    ('Yuumi'),
    ('Zac'),
    ('Zed'),
    ('Ziggs'),
    ('Zilean'),
    ('Zoe'),
    ('Zyra');

INSERT INTO LoLDB.Location([Name])
VALUES
    ('Top'),
    ('Jungle'),
    ('Mid'),
    ('Bottom'),
    ('Base');

INSERT INTO LoLDB.Objective([Name], LogoLink)
VALUES
    ('Red_Top_Outer_Turret', 'link-add-later'),
    ('Red_Top_Inner_Turret', 'link-add-later'),
    ('Red_Top_Base_Turret', 'link-add-later'),
    ('Red_Top_Inhibitor', 'link-add-later'),
    ('Red_Mid_Outer_Turret', 'link-add-later'),
    ('Red_Mid_Inner_Turret', 'link-add-later'),
    ('Red_Mid_Base_Turret', 'link-add-later'),
    ('Red_Mid_Inhibitor', 'link-add-later'),
    ('Red_Bot_Outer_Turret', 'link-add-later'),
    ('Red_Bot_Inner_Turret', 'link-add-later'),
    ('Red_Bot_Base_Turret', 'link-add-later'),
    ('Red_Bot_Inhibitor', 'link-add-later'),
    ('Red_Nexus_Turret_1', 'link-add-later'),
    ('Red_Nexus_Turret_2', 'link-add-later'),
    ('Red_Nexus', 'link-add-later'),
    ('Blue_Top_Outer_Turret', 'link-add-later'),
    ('Blue_Top_Inner_Turret', 'link-add-later'),
    ('Blue_Top_Base_Turret', 'link-add-later'),
    ('Blue_Top_Inhibitor', 'link-add-later'),
    ('Blue_Mid_Outer_Turret', 'link-add-later'),
    ('Blue_Mid_Inner_Turret', 'link-add-later'),
    ('Blue_Mid_Base_Turret', 'link-add-later'),
    ('Blue_Mid_Inhibitor', 'link-add-later'),
    ('Blue_Bot_Outer_Turret', 'link-add-later'),
    ('Blue_Bot_Inner_Turret', 'link-add-later'),
    ('Blue_Bot_Base_Turret', 'link-add-later'),
    ('Blue_Bot_Inhibitor', 'link-add-later'),
    ('Blue_Nexus_Turret_1', 'link-add-later'),
    ('Blue_Nexus_Turret_2', 'link-add-later'),
    ('Blue_Nexus', 'link-add-later'),
    ('Rift_Herald', 'link-add-later'),
    ('Baron_Nashor', 'link-add-later'),
    ('Infernal_Drake', 'link-add-later'),
    ('Mountain_Drake', 'link-add-later'),
    ('Cloud_Drake', 'link-add-later'),
    ('Ocean_Drake', 'link-add-later'),
    ('Elder_Drake', 'link-add-later');

INSERT INTO LoLDB.ItemQuality([Name])
VALUES
    ('Starter'),
    ('Component'),
    ('Boots'),
    ('Consumable'),
    ('Legendary'),
    ('Mythic');
