DELETE FROM LoLDB.Position;
DBCC CHECKIDENT ('LoLDB.Position', RESEED, 1);
DELETE FROM LoLDB.Champion;
DBCC CHECKIDENT ('LoLDB.Champion', RESEED, 1);
DELETE FROM LoLDB.SecondaryRune;
DBCC CHECKIDENT ('LoLDB.SecondaryRune', RESEED, 1);
DELETE FROM LoLDB.KeystoneRune;
DBCC CHECKIDENT ('LoLDB.KeystoneRune', RESEED, 1);
DELETE FROM LoLDB.RunePath;
DBCC CHECKIDENT ('LoLDB.RunePath', RESEED, 1);
DELETE FROM LoLDB.ShardRune;
DBCC CHECKIDENT ('LoLDB.ShardRune', RESEED, 1);
DELETE FROM LoLDB.Region;
DBCC CHECKIDENT ('LoLDB.Region', RESEED, 1);
DELETE FROM LoLDB.Location;
DBCC CHECKIDENT ('LoLDB.Region', RESEED, 1);
DELETE FROM LoLDB.Objective;
DBCC CHECKIDENT ('LoLDB.Objective', RESEED, 1);
DELETE FROM LoLDB.ItemQuality;
DBCC CHECKIDENT ('LoLDB.ItemQuality', RESEED, 1);


INSERT INTO LoLDB.Region([Name])
VALUES
    ('North America'), ('Europe'), ('LCL'), ('Japan'), ('Oceania'), ('Brazil'), ('Turkey'), ('China'), ('Korea');

INSERT INTO LoLDB.RunePath([Name], LogoLink)
VALUES
    ('Precision', 'https://static.wikia.nocookie.net/leagueoflegends/images/2/26/Precision_icon.png'),
    ('Domination', 'https://static.wikia.nocookie.net/leagueoflegends/images/1/1e/Domination_icon.png'),
    ('Sorcery', 'https://static.wikia.nocookie.net/leagueoflegends/images/c/cd/Sorcery_icon.png'),
    ('Resolve', 'https://static.wikia.nocookie.net/leagueoflegends/images/f/fa/Resolve_icon.png'),
    ('Inspiration', 'https://static.wikia.nocookie.net/leagueoflegends/images/0/0d/Inspiration_icon.png');

INSERT INTO LoLDB.KeystoneRune([Name], LogoLink, RunePathID)
SELECT D.[Name], D.LogoLink, RunePathID
FROM (
    VALUES ('Press the Attack', 'Precision', 'https://static.wikia.nocookie.net/leagueoflegends/images/6/64/Press_the_Attack_rune.png'),
        ('Lethal Tempo', 'Precision', 'https://static.wikia.nocookie.net/leagueoflegends/images/f/f2/Lethal_Tempo_rune.png'),
	('Fleet Footwork', 'Precision', 'https://static.wikia.nocookie.net/leagueoflegends/images/4/46/Fleet_Footwork_rune.png'),
	('Conqueror', 'Precision', 'https://static.wikia.nocookie.net/leagueoflegends/images/2/20/Conqueror_rune.png'),
        ('Electrocute', 'Domination', 'https://static.wikia.nocookie.net/leagueoflegends/images/0/0a/Electrocute_rune.png'),
        ('Hail of Blades', 'Domination', 'https://static.wikia.nocookie.net/leagueoflegends/images/2/2e/Hail_of_Blades_rune.png'),
        ('Predator', 'Domination', 'https://static.wikia.nocookie.net/leagueoflegends/images/2/29/Predator_rune.png'),
        ('Dark Harvest', 'Domination', 'https://static.wikia.nocookie.net/leagueoflegends/images/9/9e/Dark_Harvest_rune.png'),
        ('Phase Rush', 'Sorcery', 'https://static.wikia.nocookie.net/leagueoflegends/images/7/79/Phase_Rush_rune.png'),
        ('Arcane Comet', 'Sorcery', 'https://static.wikia.nocookie.net/leagueoflegends/images/e/e5/Arcane_Comet_rune.png'),
        ('Summon Aery', 'Sorcery', 'https://static.wikia.nocookie.net/leagueoflegends/images/d/d7/Summon_Aery_rune.png'),
        ('Grasp of the Undying', 'Resolve', 'https://static.wikia.nocookie.net/leagueoflegends/images/a/a3/Grasp_of_the_Undying_rune.png'),
        ('Aftershock', 'Resolve', 'https://static.wikia.nocookie.net/leagueoflegends/images/c/ce/Aftershock_rune.png'),
        ('Guardian', 'Resolve', 'https://static.wikia.nocookie.net/leagueoflegends/images/4/4a/Guardian_rune.png'),
        ('Prototype: Omnistone', 'Inspiration', 'https://static.wikia.nocookie.net/leagueoflegends/images/9/91/Prototype-_Omnistone_rune.png'),
        ('Glacial Augment', 'Inspiration', 'https://static.wikia.nocookie.net/leagueoflegends/images/0/03/Glacial_Augment_rune.png'),
        ('Unsealed Spellbook', 'Inspiration', 'https://static.wikia.nocookie.net/leagueoflegends/images/a/a9/Unsealed_Spellbook_rune.png')
) D([Name], RunePathName, LogoLink)
JOIN LoLDB.RunePath RP ON D.RunePathName = RP.Name;

INSERT INTO LoLDB.SecondaryRune([Name], Slot, LogoLink, RunePathID)
SELECT D.[Name], Slot, D.LogoLink, RunePathID
FROM (
    VALUES ('Overheal', 'Precision', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/6/69/Overheal_rune.png'),
	('Triumph', 'Precision', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/7/7c/Triumph_rune.png'),
	('Presence of Mind', 'Precision', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/f/f9/Presence_of_Mind_rune.png'),
        ('Legend: Alacrity', 'Precision', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/5/5e/Legend-_Alacrity_rune.png'),
        ('Legend: Tenacity', 'Precision', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/d/d4/Legend-_Tenacity_rune.png'),
        ('Legend: Bloodline', 'Precision', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/f/fb/Legend-_Bloodline_rune.png'),
        ('Coup De Grace', 'Precision', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/b/be/Coup_de_Grace_rune.png'),
        ('Cut Down', 'Precision', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/7/77/Cut_Down_rune.png'),
        ('Last Stand', 'Precision', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/0/05/Last_Stand_rune.png'),
        ('Cheap Shot', 'Domination', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/d/d5/Cheap_Shot_rune.png'),
        ('Taste of Blood', 'Domination', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/8/8d/Taste_of_Blood_rune.png'),
        ('Sudden Impact', 'Domination', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/c/c2/Sudden_Impact_rune.png'),
        ('Zombie Ward', 'Domination', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/a/af/Zombie_Ward_rune.png'),
        ('Ghost Poro', 'Domination', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/4/42/Ghost_Poro_rune.png'),
        ('Eyeball Collection', 'Domination', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/1/15/Eyeball_Collection_rune.png'),
        ('Ravenous Hunter', 'Domination', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/2/24/Ravenous_Hunter_rune.png'),
        ('Ingenious Hunter', 'Domination', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/7/71/Ingenious_Hunter_rune.png'),
        ('Relentless Hunter', 'Domination', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/f/f5/Relentless_Hunter_rune.png'),
        ('Ultimate Hunter', 'Domination', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/e/e4/Ultimate_Hunter_rune.png'),
        ('Nullifying Orb', 'Sorcery', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/8/8c/Nullifying_Orb_rune.png'),
        ('Manaflow Band', 'Sorcery', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/4/4a/Manaflow_Band_rune.png'),
        ('Nimbus Cloak', 'Sorcery', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/e/ea/Nimbus_Cloak_rune.png'),
        ('Transcendence', 'Sorcery', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/8/83/Transcendence_rune.png'),
        ('Celerity', 'Sorcery', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/4/43/Celerity_rune.png'),
        ('Absolute Focus', 'Sorcery', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/7/75/Absolute_Focus_rune.png'),
        ('Scorch', 'Sorcery', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/e/e5/Scorch_rune.png'),
        ('Waterwalking', 'Sorcery', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/a/ac/Waterwalking_rune.png'),
        ('Gathering Storm', 'Sorcery', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/8/8c/Gathering_Storm_rune.png'),
        ('Demolish', 'Resolve', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/3/3a/Demolish_rune.png'),
        ('Font of Life', 'Resolve', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/f/f6/Font_of_Life_rune.png'),
        ('Shield Bash', 'Resolve', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/9/93/Shield_Bash_rune.png'),
        ('Conditioning', 'Resolve', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/5/55/Conditioning_rune.png'),
        ('Second Wind', 'Resolve', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/6/65/Second_Wind_rune.png'),
        ('Bone Plating', 'Resolve', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/7/75/Bone_Plating_rune.png'),
        ('Overgrowth', 'Resolve', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/4/42/Overgrowth_rune.png'),
        ('Revitalize', 'Resolve', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/0/0c/Revitalize_rune.png'),
        ('Unflinching', 'Resolve', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/8/81/Unflinching_rune.png'),
        ('Hextech Flashtraption', 'Inspiration', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/7/75/Hextech_Flashtraption_rune.png'),
        ('Magical Footwear', 'Inspiration', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/f/fa/Magical_Footwear_rune.png'),
        ('Perfect Timing', 'Inspiration', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/f/f3/Perfect_Timing_rune.png'),
        ('Future''s Market', 'Inspiration', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/f/f3/Future%27s_Market_rune.png'),
        ('Minion Dematerializer', 'Inspiration', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/7/76/Minion_Dematerializer_rune.png'),
        ('Biscuit Delivery', 'Inspiration', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/8/8f/Biscuit_Delivery_rune.png'),
        ('Cosmic Insight', 'Inspiration', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/8/85/Cosmic_Insight_rune.png'),
        ('Approach Velocity', 'Inspiration', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/8/81/Approach_Velocity_rune.png'),
        ('Time Warp Tonic', 'Inspiration', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/d/d6/Time_Warp_Tonic_rune.png')
) D([Name], RunePathName, Slot, LogoLink)
JOIN LoLDB.RunePath RP ON D.RunePathName = RP.Name;

INSERT INTO LoLDB.ShardRune([Name], Slot, LogoLink)
VALUES
    ('Adaptive Force', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/a/a3/Rune_shard_Adaptive_Force.png'),
    ('Attack Speed', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/e/e4/Rune_shard_Attack_Speed.png'),
    ('Ability Haste', 1, 'https://static.wikia.nocookie.net/leagueoflegends/images/e/e1/Rune_shard_Ability_Haste.png'),
    ('Adapative Force', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/a/a3/Rune_shard_Adaptive_Force.png'),
    ('Armor', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/e/e5/Rune_shard_Armor.png'),
    ('Magic Resist', 2, 'https://static.wikia.nocookie.net/leagueoflegends/images/1/10/Rune_shard_Magic_Resistance.png'),
    ('Health', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/7/76/Rune_shard_Health.png'),
    ('Armor', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/e/e5/Rune_shard_Armor.png'),
    ('Magic Resist', 3, 'https://static.wikia.nocookie.net/leagueoflegends/images/1/10/Rune_shard_Magic_Resistance.png');

INSERT INTO LoLDB.Position([Name], LogoLink)
VALUES
    ('Top', 'https://static.wikia.nocookie.net/leagueoflegends/images/e/ef/Top_icon.png'),
    ('Jungle', 'https://static.wikia.nocookie.net/leagueoflegends/images/1/1b/Jungle_icon.png'),
    ('Mid', 'https://static.wikia.nocookie.net/leagueoflegends/images/9/98/Middle_icon.png'),
    ('ADC', 'https://static.wikia.nocookie.net/leagueoflegends/images/9/97/Bottom_icon.png'),
    ('Support', 'https://static.wikia.nocookie.net/leagueoflegends/images/e/e0/Support_icon.png'),
    ('Coach', 'https://static.wikia.nocookie.net/663e53f7-1e79-4906-95a7-2c1df4ebbada/thumbnail/width/400/height/400');

INSERT INTO LoLDB.Champion([Name])
VALUES
    ('Aatrox'),
    ('Ahri'),
    ('Akali'),
    ('Akshan'),
    ('Alistar'),
    ('Amumu'),
    ('Anivia'),
    ('Annie'),
    ('Aphelios'),
    ('Ashe'),
    ('Aurelion Sol'),
    ('Azir'),
    ('Bard'),
    ('Blitzcrank'),
    ('Brand'),
    ('Braum'),
    ('Caitlyn'),
    ('Camille'),
    ('Cassiopeia'),
    ('Cho''Gath'),
    ('Corki'),
    ('Darius'),
    ('Diana'),
    ('Draven'),
    ('Dr. Mundo'),
    ('Ekko'),
    ('Elise'),
    ('Evelynn'),
    ('Ezreal'),
    ('Fiddlesticks'),
    ('Fiora'),
    ('Fizz'),
    ('Galio'),
    ('Gangplank'),
    ('Garen'),
    ('Gnar'),
    ('Gragas'),
    ('Graves'),
    ('Gwen'),
    ('Hecarim'),
    ('Heimerdinger'),
    ('Illaoi'),
    ('Irelia'),
    ('Ivern'),
    ('Janna'),
    ('Jarvan IV'),
    ('Jax'),
    ('Jayce'),
    ('Jhin'),
    ('Jinx'),
    ('Kai''Sa'),
    ('Kalista'),
    ('Karma'),
    ('Karthus'),
    ('Kassadin'),
    ('Katarina'),
    ('Kayle'),
    ('Kayn'),
    ('Kennen'),
    ('Kha''Zix'),
    ('Kindred'),
    ('Kled'),
    ('Kog''Maw'),
    ('LeBlanc'),
    ('Lee Sin'),
    ('Leona'),
    ('Lillia'),
    ('Lissandra'),
    ('Lucian'),
    ('Lulu'),
    ('Lux'),
    ('Malphite'),
    ('Malzahar'),
    ('Maokai'),
    ('Master Yi'),
    ('Miss Fortune'),
    ('Mordekaiser'),
    ('Morgana'),
    ('Nami'),
    ('Nasus'),
    ('Nautilus'),
    ('Neeko'),
    ('Nidalee'),
    ('Nocturne'),
    ('Nunu & Willump'),
    ('Olaf'),
    ('Orianna'),
    ('Ornn'),
    ('Pantheon'),
    ('Poppy'),
    ('Pyke'),
    ('Qiyana'),
    ('Quinn'),
    ('Rakan'),
    ('Rammus'),
    ('Rek''Sai'),
    ('Rell'),
    ('Renekton'),
    ('Rengar'),
    ('Riven'),
    ('Rumble'),
    ('Ryze'),
    ('Samira'),
    ('Sejuani'),
    ('Senna'),
    ('Seraphine'),
    ('Sett'),
    ('Shaco'),
    ('Shen'),
    ('Shyvana'),
    ('Singed'),
    ('Sion'),
    ('Sivir'),
    ('Skarner'),
    ('Sona'),
    ('Soraka'),
    ('Swain'),
    ('Sylas'),
    ('Syndra'),
    ('Tahm Kench'),
    ('Taliyah'),
    ('Talon'),
    ('Taric'),
    ('Teemo'),
    ('Thresh'),
    ('Tristana'),
    ('Trundle'),
    ('Tryndamere'),
    ('Twisted Fate'),
    ('Twitch'),
    ('Udyr'),
    ('Urgot'),
    ('Varus'),
    ('Vayne'),
    ('Veigar'),
    ('Vel''Koz'),
    ('Vex'),
    ('Vi'),
    ('Viego'),
    ('Viktor'),
    ('Vladimir'),
    ('Volibear'),
    ('Warwick'),
    ('Wukong'),
    ('Xayah'),
    ('Xerath'),
    ('Xin Zhao'),
    ('Yasuo'),
    ('Yone'),
    ('Yorick'),
    ('Yuumi'),
    ('Zac'),
    ('Zed'),
    ('Ziggs'),
    ('Zilean'),
    ('Zoe'),
    ('Zyra');

INSERT INTO LoLDB.Location([Name])
VALUES
    ('Top'),
    ('Jungle'),
    ('Mid'),
    ('Bottom'),
    ('Base');

INSERT INTO LoLDB.Objective([Name], LogoLink)
VALUES
    ('Red_Top_Outer_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Top_Inner_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Top_Base_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Top_Inhibitor', 'https://static.wikia.nocookie.net/leagueoflegends/images/4/4a/Blue_Super_MinionSquare.png'),
    ('Red_Mid_Outer_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Mid_Inner_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Mid_Base_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Mid_Inhibitor', 'https://static.wikia.nocookie.net/leagueoflegends/images/4/4a/Blue_Super_MinionSquare.png'),
    ('Red_Bot_Outer_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Bot_Inner_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Bot_Base_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Bot_Inhibitor', 'https://static.wikia.nocookie.net/leagueoflegends/images/4/4a/Blue_Super_MinionSquare.png'),
    ('Red_Nexus_Turret_1', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Nexus_Turret_2', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Red_Nexus', 'https://static.wikia.nocookie.net/leagueoflegends/images/d/d2/Nexus_Obelisk.png'),
    ('Blue_Top_Outer_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Top_Inner_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Top_Base_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Top_Inhibitor', 'https://static.wikia.nocookie.net/leagueoflegends/images/4/4a/Blue_Super_MinionSquare.png'),
    ('Blue_Mid_Outer_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Mid_Inner_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Mid_Base_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Mid_Inhibitor', 'https://static.wikia.nocookie.net/leagueoflegends/images/4/4a/Blue_Super_MinionSquare.png'),
    ('Blue_Bot_Outer_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Bot_Inner_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Bot_Base_Turret', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Bot_Inhibitor', 'https://static.wikia.nocookie.net/leagueoflegends/images/4/4a/Blue_Super_MinionSquare.png'),
    ('Blue_Nexus_Turret_1', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Nexus_Turret_2', 'https://static.wikia.nocookie.net/leagueoflegends/images/8/82/Turret_icon.png'),
    ('Blue_Nexus', 'https://static.wikia.nocookie.net/leagueoflegends/images/d/d2/Nexus_Obelisk.png'),
    ('Rift_Herald', 'https://static.wikia.nocookie.net/leagueoflegends/images/c/c3/Rift_HeraldSquare.png'),
    ('Baron_Nashor', 'https://static.wikia.nocookie.net/leagueoflegends/images/3/38/Baron_NashorSquare.png'),
    ('Infernal_Drake', 'https://static.wikia.nocookie.net/leagueoflegends/images/a/a0/Infernal_DrakeSquare.png'),
    ('Mountain_Drake', 'https://static.wikia.nocookie.net/leagueoflegends/images/0/00/Mountain_DrakeSquare.png'),
    ('Cloud_Drake', 'https://static.wikia.nocookie.net/leagueoflegends/images/4/47/Cloud_DrakeSquare.png'),
    ('Ocean_Drake', 'https://static.wikia.nocookie.net/leagueoflegends/images/5/55/Ocean_DrakeSquare.png'),
    ('Elder_Drake', 'https://static.wikia.nocookie.net/leagueoflegends/images/3/34/Elder_DragonSquare.png');

INSERT INTO LoLDB.ItemQuality([Name])
VALUES
    ('Starter'),
    ('Component'),
    ('Boots'),
    ('Consumable'),
    ('Legendary'),
    ('Mythic');
